### ISSUE TITLE
Lua error hovering 14h rotational rares at 0 min [attempt to index upvalue 'L' (a nil value)]

### ISSUE THREAD

**Issue by jsutan** [zarillion/handynotes-plugins#350]
**ADDON VERSION**: HandyNotes v1.6.15; HandyNotes: Dragonflight v38

**Describe the bug**
Occurs when hovering over Dragonflight 14 hour rotational rare icons on the World Map when the rare is within the spawn window (0 minutes remaining).

**Screenshots**
<img width="317" alt="image" src="https://github.com/zarillion/handynotes-plugins/assets/6308057/5cc712ad-3929-4ea2-88cc-5c833e0a7686"> (working example, don't have a non-working example but I'll get one in 30 minutes)

Lua error:

```13x HandyNotes_Dragonflight/core/util.lua:314: attempt to index upvalue 'L' (a nil value)
[string "@HandyNotes_Dragonflight/core/util.lua"]:314: in function `GetText'
[string "@HandyNotes_Dragonflight/core/nodes.lua"]:318: in function `Render'
[string "@HandyNotes_Dragonflight/core/core.lua"]:141: in function <HandyNotes_Dragonflight/core/core.lua:140>

Locals:
self = <table> {
 __address = "000002DBB59DE120"
 SpawnTime = 1677362400
 id = 15
 __class = <table> {
 }
}
TimeFormat = "%B %d - %H:%M local time"
NextSpawn = 1684771200
TimeLeft = 53
(*temporary) = nil
(*temporary) = 1677362400
(*temporary) = 1684771200
(*temporary) = 53
(*temporary) = 1684771200
(*temporary) = 53
(*temporary) = 50400
(*temporary) = "attempt to index upvalue 'L' (a nil value)"
ns = <table> {
 GetIconLink = <function> defined @HandyNotes_Dragonflight/core/icons.lua:108
 GROUP_HIDDEN75 = <table> {
 }
 NameResolver = <table> {
 }
 DRAGON_CUSTOMIZATIONS = <table> {
 }
 color = <table> {
 }
 WorldMapDataProvider = <table> {
 }
 requirement = <table> {
 }
 SetOpt = <function> defined @HandyNotes_Dragonflight/core/options.lua:63
 status = <table> {
 }
 COLORS = <table> {
 }
 Group = <table> {
 }
 tomtom = <table> {
 }
 group_types = <table> {
 }
 maps = <table> {
 }
 world_map_button = Krowi_WorldMapButtons2 {
 }
 IsInstance = <function> defined @HandyNotes_Dragonflight/core/class.lua:86
 faction = "Alliance"
 icons = <table> {
 }
 class = "PRIEST"
 Intervals = <table> {
 }
 expansion = 10
 BootstrapDevelopmentEnvironment = <function> defined @HandyNotes_Dragonflight/core/dev.lua:30
 groups = <table> {
 }
 professions = <table> {
 }
 node = <table> {
 }
 Error = <function> defined @HandyNotes_Dragonflight/core/dev.lua:285
 reward = <table> {
 }
 optionDefaults = <table> {
 }
 options = <table> {
 }
 GetColorOpt = <function> defined @HandyNotes_Dragonflight/core/options.lua:68
 Warn = <function> defined @HandyNotes_Dragonflight/core/dev.lua:280
 GROUP_HIDDEN = <table> {
 }
 Class = <function> defined @HandyNotes_Dragonflight/core/class.lua:10
 PlayerHasProfession = <function> defined @HandyNotes_Dragonflight/core/util.lua:173
 plugin_name = "HandyNotes: Dragonflight"
 locale = <table> {
 }
 MinimapDataProvider = HandyNotes_DragonflightMinimapDP {
 }
 Map = <table> {
 }
 CreateGlobalGroupOptions = <function> defined @HandyNotes_Dragonflight/core/options.lua:338
 Interval = <table> {
 }
 GetIconPath = <function> defined @HandyNotes_Dragonflight/core/icons.lua:102
 AsTable = <function> defined @HandyNotes_Dragonflight/core/util.lua:230
 GetGlowPath = <function> defined @HandyNotes_Dragonflight/core/icons.lua:117
 RenderLinks = <function> defined @HandyNotes_Dragonflight/core/util.lua:73
 poi = <table> {
 }
 HEXtoRGBA = <function> defined @HandyNotes_Dragonflight/core/util.lua:253
 Debug = <function> defined @HandyNotes_Dragonflight/core/dev.lua:275
 addon = <table> {
 }
 GROUP_ALPHA75 = <table> {
 }
 GetOpt = <function> defined @HandyNotes_Dragonflight/core/options.lua:62
 AsIDTable = <function> defined @HandyNotes_Dragonflight/core/util.lua:238
 PrepareLinks = <function> defined @HandyNotes_Dragonflight/core/util.lua:57
 CreateGroupOptions = <function> defined @HandyNotes_Dragonflight/core/options.lua:382
 IsClass = <function> defined @HandyNotes_Dragonflight/core/class.lua:82
 NewLocale = <function> defined @HandyNotes_Dragonflight/core/util.lua:211
 Clone = <function> defined @HandyNotes_Dragonflight/core/class.lua:96
 PlayerHasItem = <function> defined @HandyNotes_Dragonflight/core/util.lua:169
 SetColorOpt = <function> defined @HandyNotes_Dragonflight/core/options.lua:73
 GetDatabaseTable = <function> defined @HandyNotes_Dragonflight/core/util.lua:185
}
L = nil
```

**Comment by Ioney** [comment]
sorry it got closed by my commit.

it should now be fixed when Zarillion releases the new version.

**Comment by Gaviin1242** [comment]
Any update on this?  Still getting this error.  Would love a release to get it fixed.  :)

**Comment by Krovikan** [comment]
Hello:

Is all done (you can verify that the Issue have the green tag "Solved next release" and the commit from @Ioney with solution: https://github.com/zarillion/handynotes-plugins/commit/087494bcbe4b5f88d25a367da8845ac744dcce54

Only needs a new release. I'll say to @zarillion (creator).

Regards
