### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Imna1975** [zarillion/handynotes-plugins#521]
**ADDON VERSION**: 126

15x HandyNotes_Legion/core/util.lua:100: attempt to index local 'str' (a nil value)
[HandyNotes_Legion/core/util.lua]:100: in function 'RenderLinks'
[HandyNotes_Legion/core/rewards.lua]:204: in function '(for generator)'
[HandyNotes_Legion/core/rewards.lua]:82: in function 'Render'
[HandyNotes_Legion/core/nodes.lua]:389: in function 'RenderRewards'
[HandyNotes_Legion/core/nodes.lua]:360: in function 'Render'
[HandyNotes_Legion/core/core.lua]:141: in function <HandyNotes_Legion/core/core.lua:140>

Locals:
str = nil
nameOnly = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'str' (a nil value)"
NameResolver = <table> {
 cache = <table> {
 }
 prepared = <table> {
 }
}
ns = <table> {
 GROUP_HIDDEN75 = <table> {
 }
 NameResolver = <table> {
 }
 api = <table> {
 }
 class = "DEATHKNIGHT"
 groups = <table> {
 }
 COLORS = <table> {
 }
 tomtom = <table> {
 }
 world_map_button = Krowi_WorldMapButtons3 {
 }
 maps = <table> {
 }
 tooltip = <table> {
 }
 icons = <table> {
 }
 plugin_name = "HandyNotes: Legion"
 hooks = <table> {
 }
 MinimapDataProvider = HandyNotes_LegionMinimapDP {
 }
 Interval = <table> {
 }
 node = <table> {
 }
 Map = <table> {
 }
 poi = <table> {
 }
 addon = <table> {
 }
 Group = <table> {
 }
 requirement = <table> {
 }
 status = <table> {
 }
 group_types = <table> {
 }
 options = <table> {
 }
 professions = <table> {
 }
 reward = <table> {
 }
 optionDefaults = <table> {
 }
 locale = <table> {
 }
 color = <table> {
 }
 WorldMapDataProvider = <table> {
 }
 faction = "Alliance"
 GROUP_ALPHA75 = <table> {
 }
 GROUP_HIDDEN = <table> {
 }
 expansion = 7
 hook = <table> {
 }
}

**Comment by mpolewaczyk** [comment]
This is caused by an incorrect implementation in issue #495

**Comment by Ioney** [comment]
when is this error happening? hovering over a specific node or when loading the game?

**Comment by TSKIV** [comment]
> when is this error happening? hovering over a specific node or when loading the game?

Im getting it only hovering over Treasure chests on map

**Comment by Ioney** [comment]
on which map?

**Comment by TSKIV** [comment]
Legion (specifically the first four zones, not getting the error on argus or the broken shore), also gives the error when hovering the Portal to Helheim in stormheim

**Comment by Ioney** [comment]
it has been fixed with 98f1bfbfd3c76507fd78fa12362d158934adac52 and will be included in the next version.

you can apply the change manually in the meantime

**Comment by nbartley** [comment]
I am still getting this on v126 on all Lemix maps. (Unsure of unopened zones)
